@startuml
'https://plantuml.com/sequence-diagram

hide footbox
actor User as U

participant ":UserInterface" as UserInterface
participant ":Parser" as Parser
participant ":DeleteTransactionCommand" as DeleteTransactionCommand
participant "<<class>>\n:User" as User
participant ":Bank" as Bank
participant ":Storage" as Storage
participant ":OutputManager" as OutputManager


title Delete Transaction Sequence Diagram


U -> UserInterface : Enters "delete 2" command
activate UserInterface

UserInterface -> Parser : parseCommand(...)
activate Parser

Parser -> User : check LoggedIn
activate User

User --> Parser
deactivate User

alt User logged in
    create DeleteTransactionCommand
    Parser -> DeleteTransactionCommand: new DeleteTransactionCommand(...)
    activate DeleteTransactionCommand
    DeleteTransactionCommand --> Parser
    deactivate DeleteTransactionCommand

else User not logged in

    Parser -> OutputManager : print error to prompt login
    activate OutputManager
    OutputManager --> U
    deactivate OutputManager
end

Parser -> DeleteTransactionCommand : execute(...)
    activate DeleteTransactionCommand

    DeleteTransactionCommand -> User : getCurrBank()
    activate User
    User --> DeleteTransactionCommand
    deactivate User
    DeleteTransactionCommand -> Bank : deleteTransactionFromBank(2)
    activate Bank

    Bank -> Bank : remove(index = 2) from transactions
    Bank --> DeleteTransactionCommand: returns Transaction
    deactivate Bank

    DeleteTransactionCommand -> OutputManager : prints delete success message and balance
    activate OutputManager
    OutputManager --> U
    deactivate OutputManager
    DeleteTransactionCommand -> User : getStorage()
    activate User
    User --> DeleteTransactionCommand
    deactivate User
    DeleteTransactionCommand -> Storage : saveTransactions(...)
    activate Storage
    Storage --> DeleteTransactionCommand
    deactivate Storage
    DeleteTransactionCommand --> Parser
    destroy DeleteTransactionCommand

Parser --> UserInterface : return shouldExit = "false"
deactivate Parser
deactivate UserInterface

@enduml
